# This file was generated by GoReleaser. DO NOT EDIT.
cask "ama2" do
  version "cli-v1.0.0"

  on_macos do
    on_intel do
      sha256 "2e922afd3075739f4de0e10c251e12605db98e16771c23b509f6b7166485baf4"
      url "https://github.com/ama2-team/ama2-public/releases/download/#{version}/ama2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db8f7ca9a92b2df4b360696040093c94e7d31d81e1a1548e99cee6a4cb5404e6"
      url "https://github.com/ama2-team/ama2-public/releases/download/#{version}/ama2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a5b5fb5020931baa32b8d3c087ac3cc43797ff032b0179ef70a91a75b2caa73"
      url "https://github.com/ama2-team/ama2-public/releases/download/#{version}/ama2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4d709e563a018b0e56de43bc32d7b5384f27641e88f44f45dffa130d482df12"
      url "https://github.com/ama2-team/ama2-public/releases/download/#{version}/ama2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ama2"
  desc "Official command-line client for AMA2 — agent-first messaging platform"
  homepage "https://ama2.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ama2"

  # No zap stanza required

end
