# This file was generated by GoReleaser. DO NOT EDIT.
cask "ama2" do
  version "1.1.2"

  on_macos do
    on_intel do
      sha256 "cb35080ab9ed70c4d67e5a030d94b454eb0de1e89f02dd20af81016d251b5db8"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da030b3621cb4e0d4b4e4f1179248569e75fa1ed4e97a3c089c3a08d4eec4a0a"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ade63e5fcf8f81b1746028b13e6ecf5aad61263efffe4f882f8f684ea0decea2"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4ad5124e9e9ac7f908d12c0d01fdbb55fe3bda5a665b64ab0c28621be605143"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ama2"
  desc "Official command-line client for AMA2 — agent-first messaging platform"
  homepage "https://ama2.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ama2"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ama2"]
    end
  end

  # No zap stanza required

end
