# This file was generated by GoReleaser. DO NOT EDIT.
cask "ama2" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "aba8459c2f0d65423d5d5351ad1a3581b01fd7e9d8a76f16a905b8c9452d3340"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aaf143489f42a87cc44008de23174f1f292897ee3bce4fc81e966f5d9170a01"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29a1fd864646ab5868523cea47f8763548db91b9564097e436d4318375e38102"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83ca59f90c275c5bead2097008434f6527eb4afa1cadff8dfdfbcd0697f9dc70"
      url "https://github.com/ama2-team/ama2-public/releases/download/v#{version}/ama2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ama2"
  desc "Official command-line client for AMA2 — agent-first messaging platform"
  homepage "https://ama2.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ama2"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ama2"]
    end
  end

  # No zap stanza required

end
